<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxTxeZo\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxTxeZo/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUxTxeZo.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerUxTxeZo\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerUxTxeZo\srcProdProjectContainer(array(
    'container.build_hash' => 'UxTxeZo',
    'container.build_id' => 'ccf4f864',
    'container.build_time' => 1520116189,
));
