<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\MicroPostController:add' => function () {
    return ($this->privates['service_locator.r959M13'] ?? $this->load(__DIR__.'/getServiceLocator_R959M13Service.php'));
}, 'App\\Controller\\MicroPostController:index' => function () {
    return ($this->privates['service_locator.dreITg8'] ?? $this->load(__DIR__.'/getServiceLocator_DreITg8Service.php'));
}, 'App\\Controller\\RegisterController:register' => function () {
    return ($this->privates['service_locator..4zswUE'] ?? $this->load(__DIR__.'/getServiceLocator__4zswUEService.php'));
}, 'App\\Controller\\SecurityController:confirm' => function () {
    return ($this->privates['service_locator.MN7kevy'] ?? $this->load(__DIR__.'/getServiceLocator_MN7kevyService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.ltE88OR'] ?? $this->load(__DIR__.'/getServiceLocator_LtE88ORService.php'));
}, 'App\\Controller\\MicroPostController::add' => function () {
    return ($this->privates['service_locator.r959M13'] ?? $this->load(__DIR__.'/getServiceLocator_R959M13Service.php'));
}, 'App\\Controller\\MicroPostController::index' => function () {
    return ($this->privates['service_locator.dreITg8'] ?? $this->load(__DIR__.'/getServiceLocator_DreITg8Service.php'));
}, 'App\\Controller\\RegisterController::register' => function () {
    return ($this->privates['service_locator..4zswUE'] ?? $this->load(__DIR__.'/getServiceLocator__4zswUEService.php'));
}, 'App\\Controller\\SecurityController::confirm' => function () {
    return ($this->privates['service_locator.MN7kevy'] ?? $this->load(__DIR__.'/getServiceLocator_MN7kevyService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.ltE88OR'] ?? $this->load(__DIR__.'/getServiceLocator_LtE88ORService.php'));
})));
